// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://joikcmrwqgpljclxbynr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpvaWtjbXJ3cWdwbGpjbHhieW5yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMTA3NzMsImV4cCI6MjA3MTc4Njc3M30.T_3xbym_rBamXm1H3n6f7rSLv1f5rAFDrL-68_V8rv4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});